---
version: '2'
services:
  consul:
    image: progrium/consul
    command: -server -bootstrap -ui-dir /ui
    hostname: node1
    ports:
      - "8500:8500"

  app:
    image: skord/maxbook
    depends_on:
      - maxscale
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql2://appuser:app-pass@maxscale:13306/maxbook_db?reaping_frequency=5&dead_connection_timeout=5&pool=2
      - RAILS_ENV=production
      - SECRET_KEY_BASE=config.secret_key=dcaa507ca8aa0a6ffe91727d5e8b5113b94e6988429f387e428e4879c4e3f4039e8c8cb4b9d809d6fd10d5d506a4b444a553b1daf906e1c014b8f2b3baf92ae4
      - RAILS_SERVE_STATIC_FILES=true

  maxpanel:
    image: skord/maxpanel:edge
    depends_on:
      - maxscale
    environment:
      - MAXSCALE_MAXINFO_JSON_LISTENER_TCP_ADDR=maxscale:8003
    ports:
      - "18080:80"

  maxscale:
    build: ../../maxscale-edge
    environment:
      - MAXSCALE_CONSUL_ADDR=consul:8500
    depends_on:
      - mrm
    expose:
      - 13306
      - 13307
      - 8003
      - 9003
    ports:
      - "13306:13306"
      - "13307:13307"
      - "8003:8003"
      - "9003:9003"

  maxscale_exporter:
    image: skord/maxscale_exporter
    environment:
      - MAXSCALE_MAXINFO_JSON_LISTENER_TCP_ADDR=maxscale:8003
      - MAXSCALE_EXPORTER_LISTEN_ADDR=:9195
    depends_on:
      - maxscale
    expose:
      - 9195
    ports:
      - 9195:9195


  mrm:
    image: tanji/replication-manager:latest
    command: monitor --daemon --interactive=false --hosts=mariadb1,mariadb2,mariadb3,mariadb4,mariadb5 --user=root:rootpassword --rpluser=repl:pass --http-server --http-bind-address=0.0.0.0
    depends_on:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
    tty: true
    ports:
      - '10001:10001'
    stdin_open: true

  mariadb1:
    image: mariadb
    build: ../../mariadb/10.1
    command: --log-bin --skip-name-resolve --server_id=1 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_BOOTSTRAP_KEY=mariadb2/bootstrapsql
    depends_on:
      - consul

  agent1:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb1 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb1

  exporter1:
    image: prom/mysqld-exporter
    expose:
      - 9104
    depends_on:
      - mariadb1
    environment:
      - DATA_SOURCE_NAME=exporter:pass@(mariadb1:3306)/
    command:
      - '-collect.perf_schema.eventsstatements=true'
      - '-collect.perf_schema.file_events=true'
      - '-collect.binlog_size=true'
      - '-collect.info_schema.processlist=true'
      - '-collect.info_schema.userstats=true'
      - '-collect.info_schema.tablestats=true'
      - '-collect.info_schema.processlist=true'
      - '-collect.info_schema.innodb_metrics=true'
      - '-collect.info_schema.query_response_time=true'
      - '-collect.perf_schema.eventswaits=true'
      - '-collect.perf_schema.file_events=true'
      - '-collect.perf_schema.indexiowaits=true'
      - '-collect.perf_schema.tableiowaits=true'
      - '-collect.perf_schema.tablelocks=true'

  mariadb2:
    image: mariadb
    build: ../../mariadb/10.1
    command: --log-bin --skip-name-resolve --server_id=2 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_BOOTSTRAP_KEY=mariadb2/bootstrapsql
    depends_on:
      - consul

  agent2:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb2 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb2

  exporter2:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb2
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb2:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'


  mariadb3:
    image: mariadb
    build: ../../mariadb/10.1
    command: --log-bin --skip-name-resolve --server_id=3 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_BOOTSTRAP_KEY=mariadb3/bootstrapsql
    depends_on:
      - consul

  agent3:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb3 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb3

  exporter3:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb3
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb3:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'

  mariadb4:
    image: mariadb
    build: ../../mariadb/10.1
    command: --log-bin --skip-name-resolve --server_id=4 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_BOOTSTRAP_KEY=mariadb4/bootstrapsql
    depends_on:
      - consul

  agent4:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb4 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb4

  agent4:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb4 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb4

  exporter4:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb4
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb4:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'

  mariadb5:
    image: mariadb
    build: ../../mariadb/10.1
    command: --log-bin --skip-name-resolve --server_id=5 --sync_binlog=1 --innodb_flush_log_at_trx_commit=1 --userstat=1 --innodb_monitor_enable=all --plugin-load=query_response_time --query_response_time_stats=1 --performance_schema=on
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_INITDB_SKIP_TZINFO=true
      - CONSUL_HTTP_ADDR=consul:8500
      - CONSUL_BOOTSTRAP_KEY=mariadb5/bootstrapsql
    depends_on:
      - consul

  agent5:
    image: tanji/replication-manager:latest
    command: agent --hosts=mariadb5 --user=root --rpluser=repl:pass
    depends_on:
      - mariadb5

  exporter5:
      image: prom/mysqld-exporter
      expose:
        - 9104
      depends_on:
        - mariadb5
      environment:
        - DATA_SOURCE_NAME=exporter:pass@(mariadb5:3306)/
      command:
        - '-collect.perf_schema.eventsstatements=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.binlog_size=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.userstats=true'
        - '-collect.info_schema.tablestats=true'
        - '-collect.info_schema.processlist=true'
        - '-collect.info_schema.innodb_metrics=true'
        - '-collect.info_schema.query_response_time=true'
        - '-collect.perf_schema.eventswaits=true'
        - '-collect.perf_schema.file_events=true'
        - '-collect.perf_schema.indexiowaits=true'
        - '-collect.perf_schema.tableiowaits=true'
        - '-collect.perf_schema.tablelocks=true'
